// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function CruelWorld(props) {
  return React.createElement("div", undefined, "Goodbye, Cruel World");
}

var make = CruelWorld;

export {
  make ,
}
/* react Not a pure module */
